<?php require 'templates/header.phtml'; ?>

<!-- Formulario de edición de reserva -->
<form action="<?php echo BASE_URL; ?>ActualizarReserva/<?php echo $reserva['id_reservacion']; ?>" method="POST">


    <label for="numeroHabitacion">Número de habitación</label>
    <input name="numeroHabitacion" type="number" class="form-control" id="numero_habitacion" 
        value="<?php echo $reserva['numero_habitacion']; ?>" required>

    <label for="fecha_entrada">Fecha de entrada</label>
    <input name="entrada" type="date" class="form-control" id="fecha_entrada" 
        value="<?php echo $reserva['fecha_entrada']; ?>" required>

    <label for="fecha_salida">Fecha de salida</label>
    <input name="salida" type="date" class="form-control" id="fecha_salida" 
        value="<?php echo $reserva['fecha_salida']; ?>" required>

    <label for="monto">Monto</label>
    <input name="monto" class="form-control" id="monto" type="number" 
        value="<?php echo $reserva['monto']; ?>" required>

    <button type="submit" class="btn btn-primary mt-2">Guardar cambios</button>
</form>

<?php require 'templates/footer.phtml'; ?>
