
<?php 
include 'templates/header.phtml';
?>

<h2>Editar cliente</h2>
<form method='POST' action="editarClient/<?= isset($client[0]) ? $client[0]->id_cliente : '' ?>">
    <label for="nombre">Nombre:</label>
    <input type="text" id="nombre" name="nombre" value="<?= isset($client[0]) ? $client[0]->nombre : '' ?>" required>
    
    <label for="apellido">Apellido:</label>
    <input type="text" id="apellido" name="apellido" value="<?= isset($client[0]) ? $client[0]->apellido : '' ?>" required>

    <label for="email">Email:</label>
    <input type="text" id="email" name="email" value="<?= isset($client[0]) ? $client[0]->email : '' ?>" required>

    <label for="telefono">Teléfono:</label>
    <input type="text" id="telefono" name="telefono" value="<?= isset($client[0]) ? $client[0]->telefono : '' ?>" required>
    
    <button type="submit">Actualizar Cliente</button>
</form>
<?php 
include 'templates/footer.phtml';
?>