<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->title ?? 'Website' ?></title>
    <link rel="stylesheet" href="<?= BASE_URL ?>app/css/estilos.css"> 
</head>
<body>
    <header>
        <h1><?= $this->title ?? 'Hotel Tandil' ?></h1>
        <nav>
            <a href="<?= BASE_URL ?>">Home</a>
            <a href="<?php echo 'listarClientes/' ?>">Ver clientes</a>
        </nav>
    </header>
