<?php include_once 'templates/header.phtml'; ?>

<h2>Lista de Reservaciones</h2>
    <table>
        <tr>
            <th>Numero de habitación</th>
            <th>Fecha de entrada</th>
            <th>Fecha de salida</th>
            <th>Monto</th>
            <th>Id reservación</th>
            <th>Acciones</th>
        </tr>
        <?php foreach ($Reservaciones as $Reservacion) { ?>
            <tr>
                <td><?php echo $Reservacion->numero_habitacion; ?></td>
                <td><?php echo $Reservacion->fecha_entrada; ?></td>
                <td><?php echo $Reservacion->fecha_salida; ?></td>
                <td><?php echo $Reservacion->monto; ?></td>
                <td><?php echo $Reservacion->id_reservacion; ?></td>
                <td>
                    <a href="<?php echo 'editarReservacion/'.$Reservacion->id_reservacion ?>">Editar</a>
                    <a href="<?php echo 'eliminarReservacion/'.$Reservacion->id_reservacion?>">Eliminar</a>
                    <a href="<?php echo BASE_URL; ?>clientes/<?php echo $Reservacion->id_cliente; ?>">Ver cliente</a>
                </td>
            </tr>
        <?php } ?>
    </table>
<?php include_once 'templates/footer.phtml'; 
      include_once 'templates/form_agregar_reserva.phtml';
?>
