<?php 
include 'templates/header.phtml';
?>

<form method="POST" action="login">
            <label for="NOMBRE">Nombre</label>
            <input type="text" id="nombre" name="nombre" required>
  
            <label for="password">passwrod</label>
            <input type="password"  id="password" name="password" required>

        <button type="submit">Ingresar</button>
    </form>
</div>
<?php 
include 'templates/footer.phtml';
?>